import React from 'react';
import { FileText, CheckCircle2, ShieldAlert } from 'lucide-react';
import { Container } from '@/components/layout/Container';
import { Section } from '@/components/layout/Section';
import { Badge } from '@/components/ui/Badge';
import { GlassCard } from '@/components/cards/GlassCard';

export const metadata = {
  title: 'Terms of Service',
  description: 'Review the IntelliForceAI Terms of Service, enterprise SLA agreements, acceptable use policies, and platform governance.',
};

export default function TermsPage() {
  return (
    <main className="w-full pt-8 pb-16 space-y-12">
      <Section spacing="sm">
        <Container size="xl">
          <div className="mx-auto max-w-3xl text-center space-y-4">
            <Badge variant="primary" icon={<FileText className="h-3 w-3" />}>
              Legal Governance
            </Badge>
            <h1 className="text-4xl font-extrabold tracking-tight sm:text-6xl text-gradient">
              Terms of Service
            </h1>
            <p className="text-base sm:text-lg text-muted-foreground leading-relaxed">
              Last Updated: August 2026 • Enterprise Contract Version 2.4
            </p>
          </div>
        </Container>
      </Section>

      <Section spacing="md" className="w-full">
        <Container size="lg">
          <GlassCard intensity="high" className="p-8 sm:p-12 space-y-8 border-primary/30">
            <div className="space-y-6 text-sm text-muted-foreground leading-relaxed">
              <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
                <CheckCircle2 className="h-5 w-5 text-emerald-400" /> 1. Service Level Availability (SLA)
              </h2>
              <p>
                IntelliForceAI guarantees 99.99% operational uptime for Dedicated Single-Tenant Enterprise VPC deployments. Service credits are automatically issued for any verified downtime exceeding SLA limits.
              </p>

              <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
                <ShieldAlert className="h-5 w-5 text-amber-400" /> 2. Acceptable Use Policy
              </h2>
              <p>
                Customers shall not utilize IntelliForceAI 2.0 multi-agent swarms for illegal malware generation, automated brute-force cyberattacks, deceptive impersonation, or actions violating international export regulations.
              </p>

              <h2 className="text-xl font-bold text-foreground">3. Intellectual Property Rights</h2>
              <p>
                Customers retain 100% ownership over all software code, trained weights, datasets, and output artifacts generated by their agent swarms. IntelliForceAI retains ownership over core Rust engine software.
              </p>

              <h2 className="text-xl font-bold text-foreground">4. Limitation of Liability</h2>
              <p>
                In no event shall IntelliForceAI Inc. be liable for indirect, incidental, or consequential damages exceeding total contract fees paid within the preceding 12-month period.
              </p>

              <h2 className="text-xl font-bold text-foreground">5. Governing Law</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of the State of California, United States.
              </p>
            </div>
          </GlassCard>
        </Container>
      </Section>
    </main>
  );
}
